### ISSUE TITLE
Asset filename collision between this gem and bootstrap-sass

### ISSUE THREAD

**Issue by z1lk** [twbs/bootstrap-rubygem#131]
I develop a CMS and would like BSv3 and BSv4 to both be available for theme-building. The assets (CSS/JS) in both repos lack version identifiers in the filenames. Therefore I don't seem to able to tell Sprockets to load the assets specifically for v3 or v4.

**Comment by glebm** [comment]
This is not a supported use-case. You could try modifying Sprockets assets paths at runtime.

**Comment by glebm** [comment]
@z1lk Another thing you could try is to use absolute paths to Bootstrap assets, see https://github.com/comfy/comfortable-mexican-sofa/issues/777

**Comment by z1lk** [comment]
Hey thanks @glebm. I'll have to try loading the JS with `File.read File.join ...`. I was trying to do something similar--inject the full path using ERB into the Sprockets `require` directive, but I couldn't get it to work. Either Sprockets directives were being processed before ERB or `require` wouldn't take an absolute path.

I'm asking out of pure curiousity--why not create symlinks to the main assets with more specific filenames? Is this bad practice for a gem?

**Comment by glebm** [comment]
Sprockets directives are processed before ERB, unfortunately.
You can't really create symlinks because you don't know where the bootstrap gem will be installed.

> I'm asking out of pure curiousity--why not create symlinks to the main assets with more specific filenames? Is this bad practice for a gem?

This is a very niche edge case, so not worth supporting in this gem because there are workarounds. Symlinks may not work on Windows depending on various external factors (global Git settings, filesystem configuration, etc).

**Comment by z1lk** [comment]
Yeah, injecting the file with Ruby works well. Thanks again @glebm
