### ISSUE TITLE
ExecJS::RuntimeError 

### ISSUE THREAD

**Issue by theeomm** [twbs/bootstrap-rubygem#152]
I'm trying to add bootstrap to my rails 5.2 app but I'm getting this error.

```
WARNING: The `text-hide()` mixin has been deprecated as of v4.1.0. It will be removed entirely in v5.
         on line 10 of C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bootstrap-4.1.0/assets/stylesheets/bootstrap/mixins/_text-hide.scss, in `text-hide'
         from line 57 of C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bootstrap-4.1.0/assets/stylesheets/bootstrap/utilities/_text.scss
         from line 14 of C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bootstrap-4.1.0/assets/stylesheets/bootstrap/_utilities.scss
         from line 41 of C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bootstrap-4.1.0/assets/stylesheets/_bootstrap.scss
         from line 2 of C:/Users/optim/Documents/dev/web/ed/app/assets/stylesheets/application.scss

Completed 500 Internal Server Error in 5081ms (ActiveRecord: 0.0ms)



ActionView::Template::Error (invalid regexp character):
     5:     <%= csrf_meta_tags %>
     6:     <%= csp_meta_tag %>
     7:
     8:     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     9:   </head>
    10:
    11:   <body>

(execjs):24250
app/views/layouts/application.html.erb:8:in `_app_views_layouts_application_html_erb__759718146_57858260'
```

**Comment by theeomm** [comment]
Decided to use webpacker and installed it via npm.

**Comment by yush93** [comment]
"invalid regexp character" Getting this error and it's so annoying. How to fix it? Anyone with any idea?

**Comment by EmmiaSilk** [comment]
I had this issue too. It seems to be a problem relating to duktape. I found a workaround that causes my app to work like normal, but I don't know if it will cause problems down the line.
```rb
# In `config/boot.rb`, changes the ExecJS runtime from Duktape to Node.
ENV['EXECJS_RUNTIME'] = 'Node'
```
-----
For people who know more about rails, you can reproduce the issue by following these steps:
1. Run the commands:
```sh
rails new myapp
cd myapp
rails generate controller Welcome index
```
2. Then replace the contents of  `config/routes.rb` with:
```rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
end
```
If you run `rails server` now, this should be a working Rails app. 

3. Terminate the server and run the command:
```sh
bundle add bootstrap
```
If you run `rails server` again, you will now run into the `invalid regexp character` again. This issue doesn't occur if you use the Node runtime for ExecJS instead of Duktape.

**Comment by StarfallProjects** [comment]
I've been having the same issue. @EmmiaSilk solved it for me (or at least provided a sanity saving workaround)

**Comment by yush93** [comment]
I ended up downloading the Bootstrap and placing it inside the assets.
Thank you
