### ISSUE TITLE
Not necessary to remove `*= require` and `*= require_tree` statements

### ISSUE THREAD

**Issue by CodyFitzpatrick** [twbs/bootstrap-rubygem#167]
This issue was originally going to be a proposed change to the README, but instead, I'd love to learn why the following - mentioned in README section ["a. Ruby on Rails"](https://github.com/twbs/bootstrap-rubygem#a-ruby-on-rails) -  is recommended:
> ... remove all the `*= require` and `*= require_tree` statements from the Sass file. Instead, use `@import` to import Sass files.

---

**In my case (on Rails 5.1), leaving these require statements as they were did not break my application or throw any errors following the install of this gem**. See the attached screenshot of the beginning of my `/app/assets/stylesheets/application.scss` file for example (where I also leave `*= require_tree .` and `*= require_self` statements.

---

To re-iterate, perhaps I am missing why it is so important to avoid utilizing Rails' pipeline for loading all other stylesheets & scripts (for instance, all those within `/app/assets/stylesheets` and `/app/assets/javascripts`  via the `*= require_tree .` statements whilst simultaneously using this gem (so long as we are NOT using Sass mixins or variables in these other stylesheets/scripts)?

**Comment by jblac** [comment]
If you use `*= require` you can't use mixins correctly in your custom css.   You remove the `*= require_tree` for much the same reason, you'll also get double inclusion and as such may get unexpected results.   

It's also helpful in the circumstance that you have a rails application with 2-3 different "applications" (a frontend, admin panel, something else?) - you don't want to have a single `application.css` file with all the css for all of these applications in it right?   Removing `*= require_tree`  makes that plausible.

Should also note, that using `@import` in sass files isn't getting rid of the Rails Asset Pipeline it's merely skirting sprockets, in fact - the folks behind rails themselves advocate using this method:  "If you want to use multiple Sass files, you should generally use the Sass @import rule instead of these Sprockets directives. When using Sprockets directives, Sass files exist within their own scope, making variables or mixins only available within the document they were defined in." - https://guides.rubyonrails.org/asset_pipeline.html

**Comment by glebm** [comment]
What @jblac said.
