### ISSUE TITLE
Broken tabs?

### ISSUE THREAD

**Issue by beanilsson** [twbs/bootstrap-rubygem#179]
I am trying to implement `tabs` in my Rails app but all I get is this:

[![enter image description here][1]][1]

So to me it looks like there some JS missing.

The code:

    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link" href="#">Tab One</a>
        Tab one content
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Tab Two</a>
        Tab two content
      </li>
    </ul>

I have followed the [instructions][2] for installing the gem so I figured I'd get everything I needed but apparently not? Other bootstrap related implementations in my app works, but they probably doesn't need any JS either. I'm not getting any errors in the browser console or in the server logs.

**Gemfile** 

    gem 'bootstrap', '~> 4.3.1'
    gem 'jquery-rails'
    gem 'sprockets-rails', '~> 3.2.1'

**application.js**

    //= require jquery3
    //= require popper
    //= require bootstrap

**application.css**

    @import "bootstrap";
I have of course googled but almost every result is from years ago, like [this][3] and [this][4].

Rails version: `6.0.0`

Ruby version: `2.5.1p57`

OS: `Ubuntu 18.04`

Browser: `Firefox 70.0`

  [1]: https://i.stack.imgur.com/GSFdp.png
  [2]: https://github.com/twbs/bootstrap-rubygem
  [3]: https://stackoverflow.com/questions/10929639/bootstrap-tabs-broken
  [4]: https://stackoverflow.com/questions/17091863/bootstrap-togglable-tabs-rails

**Comment by plusatt** [comment]
What you are getting is correct.
Add the `active` class to the link to mark the tab as active.  

Reading your comment I understand you are expecting tabs works magically but AFAIK they don't: you have to render the correct content depending on which tab is selected.  
In the end, tabs are just links so you should take an action based on that link, either by show/hide a div through JS or render a partial, ... Solutions are multiple.

Anyway, this place is about the bootstrap gem issues if I'm correct.

**Comment by beanilsson** [comment]
@plusatt I don't know if I expect it to work magically, but rather expecting the documentation to clearly explain when I have to implement logic on my own and when I don't. The reason I opened the issue here is because I'm using the gem.

**Comment by plusatt** [comment]
@beanilsson what you are looking for is logic about html and css; it has nothing to do with bootstrap, as far I know.  
You are looking for something that would load a view when a link is clicked, and also manage the state of that view to know which tab has been clicked.
What we are referring here as _Tabs_ are merely list elements `<li>` with a link inside.
Bootstrap is just visually representing the li element as tab

One (improvable) way to do this, in HAML, if you need to render a partial, would be:
```
%ul.nav.nav-tabs.nav-overflow.header-tabs
  %li.nav-item
    = link_to 'Profile', edit_customer_path(@customer.id, edit_tab: 'profile'), class: "nav-link #{ 'active' if @edit_tab == 'profile'}"

-if @edit_tab == 'profile'
  = render 'profile_form'
```
If you don't need to render a partial, you can simply use JS to show/hide a div with the content of the selected tab: if you have 3 tabs, you would render their content on the same page and then show/hide them depending by the clicked tab.  

As you can probably see, this has nothing to do with bootstrap, and it's far from being a issue with this gem.  
I guess stackoverflow is a better place for this kind of questions mainly because you would get better answers.  
The bootstrap gem is a wrapper for bootstrap, whose documentation is here https://getbootstrap.com/docs/4.3/getting-started/introduction/
