### ISSUE TITLE
Console Error - requires Tether

### ISSUE THREAD

**Issue by ethirajsrinivasan** [twbs/bootstrap-rubygem#25]
Uncaught Error: Bootstrap tooltips require Tether (http://github.hubspot.com/tether/). Console error is thrown in browser.

**Comment by glebm** [comment]
From the Readme:

> Tooltips and popovers depend on [tether][tether] for positioning.
> If you use them, add tether to the Gemfile:
>
> ```ruby
> source 'https://rails-assets.org' do
>   gem 'rails-assets-tether', '>= 1.1.0'
> end
> ```

[tether]: http://github.hubspot.com/tether/

**Comment by ethirajsrinivasan** [comment]
I am not using Tether in any place of my application but still console error is thrown. Error is thrown from the script if tether is undefined.

**Comment by glebm** [comment]
If you are requiring all of Bootstrap JS, that includes tooltips and popovers which require tether.

**Comment by samarti** [comment]
Same error here

**Comment by lequy1010** [comment]
refer my answer in here https://github.com/shakacode/bootstrap-loader/issues/48

**Comment by jch** [comment]
@ethirajsrinivasan not sure if this is still an issue for you, but I wanted to leave a fix here in case anyone else ran into it.

In your `application.js`, instead of `//= require bootstrap-sprockets`, you can expand the list and select only the components that you use. The components that depend on tether are disabled below:

```js
// Bootstrap without tether
//= require bootstrap/util
//= require bootstrap/alert
//= require bootstrap/button
//= require bootstrap/carousel
//= require bootstrap/collapse
//= require bootstrap/dropdown
//= require bootstrap/modal
//= require bootstrap/scrollspy
//= require bootstrap/tab
//# require bootstrap/tooltip   # not required
//# require bootstrap/popover  # not required
```

I'm on 4.0.0.alpha6, but you can view what this require manifest looks like for your version by opening the gem and inspecting `bootstrap-sprockets.js`:

```sh
$ bundle open bootstrap
```

**Comment by r00takaspin** [comment]
Getting same error at Chrome console.
