### ISSUE TITLE
Move to Dart Sass

### ISSUE THREAD

**Issue by SebouChu** [twbs/bootstrap-rubygem#255]
Hi!

Giving the fact that [SassC](https://sass-lang.com/blog/libsass-is-deprecated) is deprecated and that the [`sassc-rails`](https://github.com/sass/sassc-rails) gem seems dead for more than 3 years, I think the Bootstrap gem should move to Dart Sass.

The Rails organization has a wrapper, being the [`dartsass-rails`](https://github.com/rails/dartsass-rails) gem but it's **not compatible** with Sprockets.

As an alternative, the TableCheck organization made a Sprockets-compatible wrapper, beautifully named [`dartsass-sprockets`](https://github.com/tablecheck/dartsass-sprockets).

What do you think?

**Comment by glebm** [comment]
I don't use Rails much anymore but it sounds like migrating to `dartsass-sprockets` would make sense.
I'm guessing that in the post-Sprockets Rails JavaScript world this gem simply isn't needed, as one can use the npm bootstrap package directly.

**Comment by SebouChu** [comment]
Yeah, I was thinking pretty much the same thing 👍 

If no one is available on your team and if you're okay with this, I can try to fork and make the change there!

**Comment by jcoyne** [comment]
How about not specifying a sass dependency at all and leaving it up to the user to select the one that is appropriate for them?

**Comment by gravitystorm** [comment]
I just want to chime in here with my experience.

I'm a maintainer over at [OpenStreetMap](https://github.com/openstreetmap/openstreetmap-website) and the dependency on `sassc-rails` is blocking us from upgrading to bootstrap 5.2 . We are running into an issue where libsass can no longer parse it's own compressed output, with syntax that is used in bootstrap 5.2+, and that's causing problems while precompiling all our assets. More details on the exact syntax issue [in this comment](https://github.com/sass/sassc-rails/issues/174#issuecomment-1226010642)

Since libsass is dead, and the parsing problem is unlikely to be fixed there, I want to switch to dartsass-sprockets. But we can't since it's an either/or with sassc-rails vs dartsass-sprockets. And this gem has a hard runtime dependency on sassc-rails.

I'd be in favour of either proposed solution - either switching the dependency to dartsass-sprockets (as per #256), or figuring out how to drop the hardcoded sass engine dependency entirely (as per above comment). Either way, having a bootstrap-rubygem is still very useful for us, just not one that depends on a legacy unmaintained gem! :smile:

**Comment by SebouChu** [comment]
https://github.com/twbs/bootstrap-rubygem/blob/d64321517dba09fe1e949b46078da38df339c507/lib/bootstrap/engine.rb#L4

Something clean to write here maybe if we want to declare Sass as a soft dependency and let the user pick between the two gems (other than removing the gem from the current dependencies)

**Comment by glebm** [comment]
@SebouChu Yeah something along these lines would be ideal
