### ISSUE TITLE
How would you recommend to use glyphicons with Bootstrap 4

### ISSUE THREAD

**Issue by matas-zanevicius** [twbs/bootstrap-rubygem#37]
Since glyphicons do not come with bootstrap 4 by default, what would be the correct way to add them to rails app?

**Comment by cvrebert** [comment]
Please ask how-to questions on StackOverflow or other community support forums: https://github.com/twbs/bootstrap/blob/master/README.md#community

Since we don't support Glyphicons anymore, we don't have any official advice to offer you regarding how to use/integrate Glyphicons.
Although you may want to consider not using an icon font at all; see https://github.com/twbs/bootstrap/issues/16742
