### ISSUE TITLE
popper-js is only included in development when docs recommend it to be used 

### ISSUE THREAD

**Issue by mrlamroger** [twbs/bootstrap-rubygem#93]

**Comment by roooodcastro** [comment]
Just to clarify what I think @mrlamroger meant, which also confused me:

There's currently no mention of Popper on the current v4 alpha6 hosted docs, which is understandable as this is a change that will only take effect in the first beta. @mdo explained this in his last comment on twbs/bootstrap#22444.

The problem is that the README for this gem assumes Popper is already being used on a released version of Bootstrap, thus confusing some people, myself included. Nothing too serious, but the README should include a remark stating that Popper should only be added as a dependency for the first beta, and in the meanwhile to continue using Tether

**Comment by glebm** [comment]
I've added a prominent notice to the master readme pointing to the alpha readme to mitigate this confusion.
